apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: static-website
  description: Stack for static-website
  annotations:
    pulumi.com/project-slug: elischilling/static-website/00-backstage
spec:
  owner: group:default/development
  type: service
  lifecycle: experimental
